const CACHED_KEYS = {
  LOGGED_USER: "LOGGED_USER",
  LOGGED_USER_PERMISSIONS: "LOGGED_USER_PERMISSIONS",
  LOGGED_USER_ACTIONS: "LOGGED_USER_ACTIONS",
  USER_DETAILS: "USER_DETAILS",
};
export default CACHED_KEYS;
